name: "Run test"

on:
  push:
    branches:
      - "main"


jobs:
  test: 
    runs-on: ["ubuntu-latest"]
    strategy:
      matrix:
        go-version: [ '1.18', '1.20', '1.22' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install dependencies
        run: go get .

      - name: Test
        run: go test ./todo 



